name: discord-clone
services:
  mariadb:
    image: mariadb:lts-ubi9
    container_name: discord-clone-mariadb
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_DATABASE=exmple-database
      - MARIADB_ROOT_PASSWORD=my-secret-pw

    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
